"use client";

import React from "react";
import styled from "styled-components";

import { Icon } from "@usefui/icons";
import { Field, CopyButton } from "@usefui/components";

const GridLayout = styled.div`
  display: grid;
  background-color: var(--body-color);
  border-radius: var(--measurement-medium-30);
  grid-template-columns: repeat(
    auto-fill,
    minmax(calc(var(--measurement-large-80)), 1fr)
  );
  grid-gap: 0 0;
  box-sizing: border-box;
`;
const Box = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  gap: var(--measurement-medium-30);
  padding: var(--measurement-large-10);

  svg {
    fill: var(--font-color);
  }
`;

const DefaultIconList: { name: string; icon: React.ReactNode }[] = [
  { name: "Activity", icon: <Icon.Activity /> },
  { name: "Add", icon: <Icon.Add /> },
  {
    name: "Adjustment3LineHorizontal",
    icon: <Icon.Adjustment3LineHorizontal />,
  },
  { name: "Adjustment3LineVertical", icon: <Icon.Adjustment3LineVertical /> },
  { name: "AdjustmentFatHorizontal", icon: <Icon.AdjustmentFatHorizontal /> },
  { name: "AdjustmentFatVertical", icon: <Icon.AdjustmentFatVertical /> },
  { name: "AdjustmentFlatHorizontal", icon: <Icon.AdjustmentFlatHorizontal /> },
  { name: "AdjustmentFlatVertical", icon: <Icon.AdjustmentFlatVertical /> },
  { name: "AdjustmentHorizontal", icon: <Icon.AdjustmentHorizontal /> },
  { name: "AdjustmentVertical", icon: <Icon.AdjustmentVertical /> },
  { name: "AlignBottom", icon: <Icon.AlignBottom /> },
  { name: "AlignHorizontalCenter", icon: <Icon.AlignHorizontalCenter /> },
  { name: "AlignLeft", icon: <Icon.AlignLeft /> },
  { name: "AlignRight", icon: <Icon.AlignRight /> },
  { name: "AlignTop", icon: <Icon.AlignTop /> },
  { name: "AlignVerticalCenter", icon: <Icon.AlignVerticalCenter /> },
  { name: "Annotation", icon: <Icon.Annotation /> },
  { name: "Announcement", icon: <Icon.Announcement /> },
  { name: "AnnouncementLouder", icon: <Icon.AnnouncementLouder /> },
  { name: "AnnouncementNarrow", icon: <Icon.AnnouncementNarrow /> },
  { name: "Apple", icon: <Icon.Apple /> },
  { name: "Archive", icon: <Icon.Archive /> },
  { name: "ArrowCircleDownLeft", icon: <Icon.ArrowCircleDownLeft /> },
  { name: "ArrowCircleDownRight", icon: <Icon.ArrowCircleDownRight /> },
  { name: "ArrowCircleLeft", icon: <Icon.ArrowCircleLeft /> },
  { name: "ArrowCircleRight", icon: <Icon.ArrowCircleRight /> },
  { name: "ArrowCircleUp", icon: <Icon.ArrowCircleUp /> },
  { name: "ArrowCircleUpLeft", icon: <Icon.ArrowCircleUpLeft /> },
  { name: "ArrowCircleUpRight", icon: <Icon.ArrowCircleUpRight /> },
  { name: "ArrowCornerDownLeft", icon: <Icon.ArrowCornerDownLeft /> },
  { name: "ArrowCornerDownRight", icon: <Icon.ArrowCornerDownRight /> },
  { name: "ArrowCornerLeftDown", icon: <Icon.ArrowCornerLeftDown /> },
  { name: "ArrowCornerLeftUp", icon: <Icon.ArrowCornerLeftUp /> },
  { name: "ArrowCornerRightDown", icon: <Icon.ArrowCornerRightDown /> },
  { name: "ArrowCornerRightUp", icon: <Icon.ArrowCornerRightUp /> },
  { name: "ArrowCornerUpLeft", icon: <Icon.ArrowCornerUpLeft /> },
  { name: "ArrowCornerUpRight", icon: <Icon.ArrowCornerUpRight /> },
  { name: "ArrowDown", icon: <Icon.ArrowDown /> },
  { name: "ArrowDownEnd", icon: <Icon.ArrowDownEnd /> },
  { name: "ArrowDownLeft", icon: <Icon.ArrowDownLeft /> },
  { name: "ArrowDownRight", icon: <Icon.ArrowDownRight /> },
  { name: "ArrowFatDown", icon: <Icon.ArrowFatDown /> },
  { name: "ArrowFatDownLeft", icon: <Icon.ArrowFatDownLeft /> },
  { name: "ArrowFatDownRight", icon: <Icon.ArrowFatDownRight /> },
  { name: "ArrowFatLeft", icon: <Icon.ArrowFatLeft /> },
  { name: "ArrowFatRight", icon: <Icon.ArrowFatRight /> },
  { name: "ArrowFatUp", icon: <Icon.ArrowFatUp /> },
  { name: "ArrowFatUpLeft", icon: <Icon.ArrowFatUpLeft /> },
  { name: "ArrowFatUpRight", icon: <Icon.ArrowFatUpRight /> },
  { name: "ArrowHalfDown", icon: <Icon.ArrowHalfDown /> },
  { name: "ArrowHalfDownLeft", icon: <Icon.ArrowHalfDownLeft /> },
  { name: "ArrowHalfDownRight", icon: <Icon.ArrowHalfDownRight /> },
  { name: "ArrowHalfLeft", icon: <Icon.ArrowHalfLeft /> },
  { name: "ArrowHalfRight", icon: <Icon.ArrowHalfRight /> },
  { name: "ArrowHalfUp", icon: <Icon.ArrowHalfUp /> },
  { name: "ArrowHalfUpLeft", icon: <Icon.ArrowHalfUpLeft /> },
  { name: "ArrowHalfUpRight", icon: <Icon.ArrowHalfUpRight /> },
  { name: "ArrowLeft", icon: <Icon.ArrowLeft /> },
  { name: "ArrowLeftEnd", icon: <Icon.ArrowLeftEnd /> },
  { name: "ArrowMoveDown", icon: <Icon.ArrowMoveDown /> },
  { name: "ArrowMoveLeft", icon: <Icon.ArrowMoveLeft /> },
  { name: "ArrowMoveRight", icon: <Icon.ArrowMoveRight /> },
  { name: "ArrowMoveUp", icon: <Icon.ArrowMoveUp /> },
  { name: "ArrowRight", icon: <Icon.ArrowRight /> },
  { name: "ArrowRightEnd", icon: <Icon.ArrowRightEnd /> },
  { name: "ArrowSingleDown", icon: <Icon.ArrowSingleDown /> },
  { name: "ArrowSingleLeft", icon: <Icon.ArrowSingleLeft /> },
  { name: "ArrowSingleRight", icon: <Icon.ArrowSingleRight /> },
  { name: "ArrowSingleUp", icon: <Icon.ArrowSingleUp /> },
  { name: "ArrowSquareDown", icon: <Icon.ArrowSquareDown /> },
  { name: "ArrowSquareDownLeft", icon: <Icon.ArrowSquareDownLeft /> },
  { name: "ArrowSquareDownRight", icon: <Icon.ArrowSquareDownRight /> },
  { name: "ArrowSquareLeft", icon: <Icon.ArrowSquareLeft /> },
  { name: "ArrowSquareRight", icon: <Icon.ArrowSquareRight /> },
  { name: "ArrowSquareUp", icon: <Icon.ArrowSquareUp /> },
  { name: "ArrowSquareUpLeft", icon: <Icon.ArrowSquareUpLeft /> },
  { name: "ArrowSquareUpRight", icon: <Icon.ArrowSquareUpRight /> },
  { name: "ArrowUp", icon: <Icon.ArrowUp /> },
  { name: "ArrowUpEnd", icon: <Icon.ArrowUpEnd /> },
  { name: "ArrowUpLeft", icon: <Icon.ArrowUpLeft /> },
  { name: "ArrowUpRight", icon: <Icon.ArrowUpRight /> },
  { name: "Asterisk", icon: <Icon.Asterisk /> },
  { name: "AtSign", icon: <Icon.AtSign /> },
  { name: "AtSignSquare", icon: <Icon.AtSignSquare /> },
  { name: "Background", icon: <Icon.Background /> },
  { name: "BackwardItem", icon: <Icon.BackwardItem /> },
  { name: "BarCode", icon: <Icon.BarCode /> },
  { name: "BarCodeScan", icon: <Icon.BarCodeScan /> },
  { name: "Behance", icon: <Icon.Behance /> },
  { name: "Bell", icon: <Icon.Bell /> },
  { name: "BellOff", icon: <Icon.BellOff /> },
  { name: "BellRounded", icon: <Icon.BellRounded /> },
  { name: "BellRoundedOff", icon: <Icon.BellRoundedOff /> },
  { name: "Bezier", icon: <Icon.Bezier /> },
  { name: "BezierPenTool", icon: <Icon.BezierPenTool /> },
  { name: "Block", icon: <Icon.Block /> },
  { name: "BlockOctagon", icon: <Icon.BlockOctagon /> },
  { name: "Blur", icon: <Icon.Blur /> },
  { name: "Bookmark", icon: <Icon.Bookmark /> },
  { name: "BookmarkAdd", icon: <Icon.BookmarkAdd /> },
  { name: "BookmarkCheck", icon: <Icon.BookmarkCheck /> },
  { name: "BookmarkDownload", icon: <Icon.BookmarkDownload /> },
  { name: "BookmarkEdit", icon: <Icon.BookmarkEdit /> },
  { name: "BookmarkFavorite", icon: <Icon.BookmarkFavorite /> },
  { name: "BookmarkFind", icon: <Icon.BookmarkFind /> },
  { name: "BookmarkMinus", icon: <Icon.BookmarkMinus /> },
  { name: "BookmarkOff", icon: <Icon.BookmarkOff /> },
  { name: "BookmarkRefresh", icon: <Icon.BookmarkRefresh /> },
  { name: "BookmarkRemove", icon: <Icon.BookmarkRemove /> },
  { name: "Brackets", icon: <Icon.Brackets /> },
  { name: "Browser", icon: <Icon.Browser /> },
  { name: "Brush", icon: <Icon.Brush /> },
  { name: "BrushPaint", icon: <Icon.BrushPaint /> },
  { name: "BuildingBank", icon: <Icon.BuildingBank /> },
  { name: "BuildingChurch", icon: <Icon.BuildingChurch /> },
  { name: "BuildingHospital", icon: <Icon.BuildingHospital /> },
  { name: "BuildingOffice", icon: <Icon.BuildingOffice /> },
  { name: "BuildingOfficeSkew", icon: <Icon.BuildingOfficeSkew /> },
  { name: "BuildingStock", icon: <Icon.BuildingStock /> },
  { name: "BuildingTree", icon: <Icon.BuildingTree /> },
  { name: "Cake", icon: <Icon.Cake /> },
  { name: "Call", icon: <Icon.Call /> },
  { name: "CallAdd", icon: <Icon.CallAdd /> },
  { name: "CallEnd", icon: <Icon.CallEnd /> },
  { name: "CallMinus", icon: <Icon.CallMinus /> },
  { name: "CallPause", icon: <Icon.CallPause /> },
  { name: "Category", icon: <Icon.Category /> },
  { name: "CategoryAdd", icon: <Icon.CategoryAdd /> },
  { name: "CategoryCircle", icon: <Icon.CategoryCircle /> },
  { name: "CategoryCircleAdd", icon: <Icon.CategoryCircleAdd /> },
  { name: "CategorySquare", icon: <Icon.CategorySquare /> },
  { name: "CategorySquareAdd", icon: <Icon.CategorySquareAdd /> },
  { name: "Check", icon: <Icon.Check /> },
  { name: "CheckVerify", icon: <Icon.CheckVerify /> },
  { name: "ChevCircleDown", icon: <Icon.ChevCircleDown /> },
  { name: "ChevCircleLeft", icon: <Icon.ChevCircleLeft /> },
  { name: "ChevCircleRight", icon: <Icon.ChevCircleRight /> },
  { name: "ChevCircleUp", icon: <Icon.ChevCircleUp /> },
  { name: "ChevSquareDown", icon: <Icon.ChevSquareDown /> },
  { name: "ChevSquareLeft", icon: <Icon.ChevSquareLeft /> },
  { name: "ChevSquareRight", icon: <Icon.ChevSquareRight /> },
  { name: "ChevSquareUp", icon: <Icon.ChevSquareUp /> },
  { name: "ChevronDown", icon: <Icon.ChevronDown /> },
  { name: "ChevronDownDouble", icon: <Icon.ChevronDownDouble /> },
  { name: "ChevronLeft", icon: <Icon.ChevronLeft /> },
  { name: "ChevronLeftDouble", icon: <Icon.ChevronLeftDouble /> },
  { name: "ChevronRight", icon: <Icon.ChevronRight /> },
  { name: "ChevronRightDouble", icon: <Icon.ChevronRightDouble /> },
  {
    name: "ChevronSelectorHorizontal",
    icon: <Icon.ChevronSelectorHorizontal />,
  },
  { name: "ChevronSelectorVertical", icon: <Icon.ChevronSelectorVertical /> },
  { name: "ChevronUp", icon: <Icon.ChevronUp /> },
  { name: "ChevronUpDouble", icon: <Icon.ChevronUpDouble /> },
  { name: "Circle", icon: <Icon.Circle /> },
  { name: "Code", icon: <Icon.Code /> },
  { name: "CodeAnnotation", icon: <Icon.CodeAnnotation /> },
  { name: "CodeBrackets", icon: <Icon.CodeBrackets /> },
  { name: "CodeBrowser", icon: <Icon.CodeBrowser /> },
  { name: "CodeCircle", icon: <Icon.CodeCircle /> },
  { name: "CodeFile", icon: <Icon.CodeFile /> },
  { name: "CodeFolder", icon: <Icon.CodeFolder /> },
  { name: "CodeFunction", icon: <Icon.CodeFunction /> },
  { name: "CodeLine", icon: <Icon.CodeLine /> },
  { name: "CodeLineCircle", icon: <Icon.CodeLineCircle /> },
  { name: "CodeLineSquare", icon: <Icon.CodeLineSquare /> },
  { name: "CodeSquare", icon: <Icon.CodeSquare /> },
  { name: "Collapse", icon: <Icon.Collapse /> },
  { name: "CollapseSimple", icon: <Icon.CollapseSimple /> },
  { name: "ColorSwatch", icon: <Icon.ColorSwatch /> },
  { name: "Colors", icon: <Icon.Colors /> },
  { name: "ColorsBlen", icon: <Icon.ColorsBlen /> },
  { name: "ColorsPalette", icon: <Icon.ColorsPalette /> },
  { name: "Command", icon: <Icon.Command /> },
  { name: "CommandSquare", icon: <Icon.CommandSquare /> },
  { name: "Community", icon: <Icon.Community /> },
  { name: "Component", icon: <Icon.Component /> },
  { name: "Copy", icon: <Icon.Copy /> },
  { name: "CopyCheck", icon: <Icon.CopyCheck /> },
  { name: "CopyDashed", icon: <Icon.CopyDashed /> },
  { name: "CopyLayers", icon: <Icon.CopyLayers /> },
  { name: "Crop", icon: <Icon.Crop /> },
  { name: "Crown", icon: <Icon.Crown /> },
  { name: "Cube", icon: <Icon.Cube /> },
  { name: "Cup", icon: <Icon.Cup /> },
  { name: "Cursor", icon: <Icon.Cursor /> },
  { name: "CursorClick", icon: <Icon.CursorClick /> },
  { name: "CursorOnBox", icon: <Icon.CursorOnBox /> },
  { name: "Database3Packs", icon: <Icon.Database3Packs /> },
  { name: "Database4Packs", icon: <Icon.Database4Packs /> },
  { name: "DatabaseCloud", icon: <Icon.DatabaseCloud /> },
  { name: "DeleteX", icon: <Icon.DeleteX /> },
  { name: "Diamond", icon: <Icon.Diamond /> },
  { name: "DistributeHorizontal", icon: <Icon.DistributeHorizontal /> },
  { name: "DistributeVertical", icon: <Icon.DistributeVertical /> },
  { name: "DockBottom", icon: <Icon.DockBottom /> },
  { name: "DockLeft", icon: <Icon.DockLeft /> },
  { name: "DockRight", icon: <Icon.DockRight /> },
  { name: "DockTop", icon: <Icon.DockTop /> },
  { name: "Download", icon: <Icon.Download /> },
  { name: "DownloadCircle", icon: <Icon.DownloadCircle /> },
  { name: "DownloadCloud", icon: <Icon.DownloadCloud /> },
  { name: "Dribbble", icon: <Icon.Dribbble /> },
  { name: "Dropbox", icon: <Icon.Dropbox /> },
  { name: "Dropper", icon: <Icon.Dropper /> },
  { name: "Duplicate", icon: <Icon.Duplicate /> },
  { name: "Edit", icon: <Icon.Edit /> },
  { name: "EditCircle", icon: <Icon.EditCircle /> },
  { name: "EditLine", icon: <Icon.EditLine /> },
  { name: "EditNarrow", icon: <Icon.EditNarrow /> },
  { name: "EditNarrowCircle", icon: <Icon.EditNarrowCircle /> },
  { name: "EditNarrowLine", icon: <Icon.EditNarrowLine /> },
  { name: "EditNarrowSquare", icon: <Icon.EditNarrowSquare /> },
  { name: "EditSquare", icon: <Icon.EditSquare /> },
  { name: "ElementHorizontal", icon: <Icon.ElementHorizontal /> },
  { name: "ElementVertical", icon: <Icon.ElementVertical /> },
  { name: "EmotionHappyCircle", icon: <Icon.EmotionHappyCircle /> },
  { name: "EmotionHappySquare", icon: <Icon.EmotionHappySquare /> },
  { name: "EmotionNormalCircle", icon: <Icon.EmotionNormalCircle /> },
  { name: "EmotionNormalSquare", icon: <Icon.EmotionNormalSquare /> },
  { name: "EmotionPuzzledCircle", icon: <Icon.EmotionPuzzledCircle /> },
  { name: "EmotionPuzzledSquare", icon: <Icon.EmotionPuzzledSquare /> },
  { name: "EmotionSadCircle", icon: <Icon.EmotionSadCircle /> },
  { name: "EmotionSadSquare", icon: <Icon.EmotionSadSquare /> },
  { name: "EmotionSatisfiedCircle", icon: <Icon.EmotionSatisfiedCircle /> },
  { name: "EmotionSatisfiedSquare", icon: <Icon.EmotionSatisfiedSquare /> },
  { name: "Eraser", icon: <Icon.Eraser /> },
  { name: "Expand", icon: <Icon.Expand /> },
  { name: "ExpandSimple", icon: <Icon.ExpandSimple /> },
  { name: "Eye", icon: <Icon.Eye /> },
  { name: "EyeOff", icon: <Icon.EyeOff /> },
  { name: "FaceId", icon: <Icon.FaceId /> },
  { name: "Facebook", icon: <Icon.Facebook /> },
  { name: "Feather", icon: <Icon.Feather /> },
  { name: "Female", icon: <Icon.Female /> },
  { name: "Figma", icon: <Icon.Figma /> },
  { name: "Filter", icon: <Icon.Filter /> },
  { name: "FilterAdd", icon: <Icon.FilterAdd /> },
  { name: "FilterLine", icon: <Icon.FilterLine /> },
  { name: "FilterLineAdd", icon: <Icon.FilterLineAdd /> },
  { name: "FilterMinus", icon: <Icon.FilterMinus /> },
  { name: "Fingerprint", icon: <Icon.Fingerprint /> },
  { name: "FitHorizontal", icon: <Icon.FitHorizontal /> },
  { name: "FitVertical", icon: <Icon.FitVertical /> },
  { name: "Fitness", icon: <Icon.Fitness /> },
  { name: "Flag", icon: <Icon.Flag /> },
  { name: "FlagFly", icon: <Icon.FlagFly /> },
  { name: "FlagRectangle", icon: <Icon.FlagRectangle /> },
  { name: "FlagTriangle", icon: <Icon.FlagTriangle /> },
  { name: "FlowsHorizontal", icon: <Icon.FlowsHorizontal /> },
  { name: "FlowsHorizontalCenter", icon: <Icon.FlowsHorizontalCenter /> },
  { name: "FlowsRounded", icon: <Icon.FlowsRounded /> },
  { name: "FlowsVertical", icon: <Icon.FlowsVertical /> },
  { name: "FlowsVerticalCenter", icon: <Icon.FlowsVerticalCenter /> },
  { name: "Footer", icon: <Icon.Footer /> },
  { name: "ForwardItem", icon: <Icon.ForwardItem /> },
  { name: "Framer", icon: <Icon.Framer /> },
  { name: "Gay", icon: <Icon.Gay /> },
  { name: "Gemini", icon: <Icon.Gemini /> },
  { name: "Gender", icon: <Icon.Gender /> },
  { name: "GitBranch", icon: <Icon.GitBranch /> },
  { name: "GitCommit", icon: <Icon.GitCommit /> },
  { name: "GitMerge", icon: <Icon.GitMerge /> },
  { name: "GitPull", icon: <Icon.GitPull /> },
  { name: "Gmail", icon: <Icon.Gmail /> },
  { name: "Google", icon: <Icon.Google /> },
  { name: "Group", icon: <Icon.Group /> },
  { name: "Hand", icon: <Icon.Hand /> },
  { name: "HandNarrow", icon: <Icon.HandNarrow /> },
  { name: "Hashtag", icon: <Icon.Hashtag /> },
  { name: "HashtagCircle", icon: <Icon.HashtagCircle /> },
  { name: "HashtagSquare", icon: <Icon.HashtagSquare /> },
  { name: "Header", icon: <Icon.Header /> },
  { name: "Heart", icon: <Icon.Heart /> },
  { name: "HeartOff", icon: <Icon.HeartOff /> },
  { name: "Height", icon: <Icon.Height /> },
  { name: "Hexagon", icon: <Icon.Hexagon /> },
  { name: "Home", icon: <Icon.Home /> },
  { name: "HomeDoor", icon: <Icon.HomeDoor /> },
  { name: "HomeHappy", icon: <Icon.HomeHappy /> },
  { name: "HomeRoof", icon: <Icon.HomeRoof /> },
  { name: "HomeWindow", icon: <Icon.HomeWindow /> },
  { name: "InfinitySign", icon: <Icon.InfinitySign /> },
  { name: "InfoCircle", icon: <Icon.InfoCircle /> },
  { name: "InfoOctagon", icon: <Icon.InfoOctagon /> },
  { name: "InfoSquare", icon: <Icon.InfoSquare /> },
  { name: "Instagram", icon: <Icon.Instagram /> },
  { name: "Instance", icon: <Icon.Instance /> },
  { name: "IntegrationPiece", icon: <Icon.IntegrationPiece /> },
  { name: "IntegrationPlug", icon: <Icon.IntegrationPlug /> },
  { name: "JsCode", icon: <Icon.JsCode /> },
  { name: "Kanban", icon: <Icon.Kanban /> },
  { name: "Key", icon: <Icon.Key /> },
  { name: "KeyVertical", icon: <Icon.KeyVertical /> },
  { name: "LayoutBottom", icon: <Icon.LayoutBottom /> },
  { name: "LayoutLeft", icon: <Icon.LayoutLeft /> },
  { name: "LayoutRight", icon: <Icon.LayoutRight /> },
  { name: "LayoutTop", icon: <Icon.LayoutTop /> },
  { name: "Lesbian", icon: <Icon.Lesbian /> },
  { name: "Like", icon: <Icon.Like /> },
  { name: "LinkBroken", icon: <Icon.LinkBroken /> },
  { name: "LinkExternal", icon: <Icon.LinkExternal /> },
  { name: "LinkFlatBroken", icon: <Icon.LinkFlatBroken /> },
  { name: "LinkFlatHorizontal", icon: <Icon.LinkFlatHorizontal /> },
  { name: "LinkFlatOff", icon: <Icon.LinkFlatOff /> },
  { name: "LinkFlatSkew", icon: <Icon.LinkFlatSkew /> },
  { name: "LinkFlatVertical", icon: <Icon.LinkFlatVertical /> },
  { name: "LinkHorizontal", icon: <Icon.LinkHorizontal /> },
  { name: "LinkOff", icon: <Icon.LinkOff /> },
  { name: "LinkSkew", icon: <Icon.LinkSkew /> },
  { name: "LinkVertical", icon: <Icon.LinkVertical /> },
  { name: "List", icon: <Icon.List /> },
  { name: "ListCheck", icon: <Icon.ListCheck /> },
  { name: "LlamaMeta", icon: <Icon.LlamaMeta /> },
  { name: "Loading", icon: <Icon.Loading /> },
  { name: "LoadingDots", icon: <Icon.LoadingDots /> },
  { name: "LockCircle", icon: <Icon.LockCircle /> },
  { name: "LockCircleDots", icon: <Icon.LockCircleDots /> },
  { name: "LockCircleKey", icon: <Icon.LockCircleKey /> },
  { name: "LockCircleOff", icon: <Icon.LockCircleOff /> },
  { name: "LockNarrow", icon: <Icon.LockNarrow /> },
  { name: "LockNarrowDots", icon: <Icon.LockNarrowDots /> },
  { name: "LockNarrowKey", icon: <Icon.LockNarrowKey /> },
  { name: "LockNarrowOff", icon: <Icon.LockNarrowOff /> },
  { name: "LockSquare", icon: <Icon.LockSquare /> },
  { name: "LockSquareDots", icon: <Icon.LockSquareDots /> },
  { name: "LockSquareKey", icon: <Icon.LockSquareKey /> },
  { name: "LockSquareOff", icon: <Icon.LockSquareOff /> },
  { name: "Login", icon: <Icon.Login /> },
  { name: "LoginCircle", icon: <Icon.LoginCircle /> },
  { name: "LoginSquare", icon: <Icon.LoginSquare /> },
  { name: "LoginUser", icon: <Icon.LoginUser /> },
  { name: "LoginUserSquare", icon: <Icon.LoginUserSquare /> },
  { name: "Logout", icon: <Icon.Logout /> },
  { name: "LogoutCircle", icon: <Icon.LogoutCircle /> },
  { name: "LogoutSquare", icon: <Icon.LogoutSquare /> },
  { name: "LogoutUser", icon: <Icon.LogoutUser /> },
  { name: "LogoutUserSquare", icon: <Icon.LogoutUserSquare /> },
  { name: "Loop", icon: <Icon.Loop /> },
  { name: "Luggage", icon: <Icon.Luggage /> },
  { name: "Magic", icon: <Icon.Magic /> },
  { name: "MagicFat", icon: <Icon.MagicFat /> },
  { name: "MagicStarLeft", icon: <Icon.MagicStarLeft /> },
  { name: "MagicStarRight", icon: <Icon.MagicStarRight /> },
  { name: "Male", icon: <Icon.Male /> },
  { name: "Mask", icon: <Icon.Mask /> },
  { name: "Maximize", icon: <Icon.Maximize /> },
  { name: "MaximizeBroken", icon: <Icon.MaximizeBroken /> },
  { name: "Medal", icon: <Icon.Medal /> },
  { name: "MedalAward", icon: <Icon.MedalAward /> },
  { name: "MedalStar", icon: <Icon.MedalStar /> },
  { name: "Menu", icon: <Icon.Menu /> },
  { name: "Menu2Line", icon: <Icon.Menu2Line /> },
  { name: "MenuArrowLeft", icon: <Icon.MenuArrowLeft /> },
  { name: "MenuArrowRight", icon: <Icon.MenuArrowRight /> },
  { name: "MenuSkew", icon: <Icon.MenuSkew /> },
  { name: "Messenger", icon: <Icon.Messenger /> },
  { name: "Minus", icon: <Icon.Minus /> },
  { name: "MinusCircle", icon: <Icon.MinusCircle /> },
  { name: "MinusSquare", icon: <Icon.MinusSquare /> },
  { name: "Moon", icon: <Icon.Moon /> },
  { name: "Move", icon: <Icon.Move /> },
  { name: "Notification", icon: <Icon.Notification /> },
  { name: "NotificationAdd", icon: <Icon.NotificationAdd /> },
  { name: "Octagon", icon: <Icon.Octagon /> },
  { name: "OpenAi", icon: <Icon.OpenAi /> },
  { name: "Organization", icon: <Icon.Organization /> },
  { name: "Package", icon: <Icon.Package /> },
  { name: "Paint", icon: <Icon.Paint /> },
  { name: "Passport", icon: <Icon.Passport /> },
  { name: "PasswordCircle", icon: <Icon.PasswordCircle /> },
  { name: "PasswordSquare", icon: <Icon.PasswordSquare /> },
  { name: "Paypal", icon: <Icon.Paypal /> },
  { name: "PenTool", icon: <Icon.PenTool /> },
  { name: "PenToolAdd", icon: <Icon.PenToolAdd /> },
  { name: "PenToolMinus", icon: <Icon.PenToolMinus /> },
  { name: "PenToolUp", icon: <Icon.PenToolUp /> },
  { name: "Pencil", icon: <Icon.Pencil /> },
  { name: "Percent", icon: <Icon.Percent /> },
  { name: "PercentCircle", icon: <Icon.PercentCircle /> },
  { name: "PercentSquare", icon: <Icon.PercentSquare /> },
  { name: "Pet", icon: <Icon.Pet /> },
  { name: "Phone", icon: <Icon.Phone /> },
  { name: "Pin", icon: <Icon.Pin /> },
  { name: "PinOff", icon: <Icon.PinOff /> },
  { name: "PinRounded", icon: <Icon.PinRounded /> },
  { name: "PinRoundedOff", icon: <Icon.PinRoundedOff /> },
  { name: "PinRoundedSkew", icon: <Icon.PinRoundedSkew /> },
  { name: "PinSkew", icon: <Icon.PinSkew /> },
  { name: "Pinterest", icon: <Icon.Pinterest /> },
  { name: "Playstore", icon: <Icon.Playstore /> },
  { name: "Polygon", icon: <Icon.Polygon /> },
  { name: "PositionBottom", icon: <Icon.PositionBottom /> },
  { name: "PositionBottomLeft", icon: <Icon.PositionBottomLeft /> },
  { name: "PositionBottomRight", icon: <Icon.PositionBottomRight /> },
  { name: "PositionCenter", icon: <Icon.PositionCenter /> },
  { name: "PositionLeft", icon: <Icon.PositionLeft /> },
  { name: "PositionRight", icon: <Icon.PositionRight /> },
  { name: "PositionTop", icon: <Icon.PositionTop /> },
  { name: "PositionTopLeft", icon: <Icon.PositionTopLeft /> },
  { name: "PositionTopRight", icon: <Icon.PositionTopRight /> },
  { name: "QrCode", icon: <Icon.QrCode /> },
  { name: "QrCodeScan", icon: <Icon.QrCodeScan /> },
  { name: "Question", icon: <Icon.Question /> },
  { name: "QuestionCircle", icon: <Icon.QuestionCircle /> },
  { name: "QuestionSquare", icon: <Icon.QuestionSquare /> },
  { name: "Ranking", icon: <Icon.Ranking /> },
  { name: "Redit", icon: <Icon.Redit /> },
  { name: "Redo", icon: <Icon.Redo /> },
  { name: "ReflectHorizontal", icon: <Icon.ReflectHorizontal /> },
  { name: "ReflectVertical", icon: <Icon.ReflectVertical /> },
  { name: "RefreshHorizontal", icon: <Icon.RefreshHorizontal /> },
  { name: "RefreshVertical", icon: <Icon.RefreshVertical /> },
  { name: "Reload", icon: <Icon.Reload /> },
  { name: "ReloadReverse", icon: <Icon.ReloadReverse /> },
  { name: "Remove", icon: <Icon.Remove /> },
  { name: "RemoveCircle", icon: <Icon.RemoveCircle /> },
  { name: "RemoveSquare", icon: <Icon.RemoveSquare /> },
  { name: "RuleHorizontal", icon: <Icon.RuleHorizontal /> },
  { name: "RulePencil", icon: <Icon.RulePencil /> },
  { name: "RuleSkew", icon: <Icon.RuleSkew /> },
  { name: "RuleVertical", icon: <Icon.RuleVertical /> },
  { name: "RunwayMl", icon: <Icon.RunwayMl /> },
  { name: "Save", icon: <Icon.Save /> },
  { name: "ScaleDown", icon: <Icon.ScaleDown /> },
  { name: "ScaleUp", icon: <Icon.ScaleUp /> },
  { name: "ScanHorizontal", icon: <Icon.ScanHorizontal /> },
  { name: "ScanPassword", icon: <Icon.ScanPassword /> },
  { name: "ScanVertical", icon: <Icon.ScanVertical /> },
  { name: "ScissorsCut", icon: <Icon.ScissorsCut /> },
  { name: "ScissorsOpen", icon: <Icon.ScissorsOpen /> },
  { name: "Search", icon: <Icon.Search /> },
  { name: "SearchAdd", icon: <Icon.SearchAdd /> },
  { name: "SearchFat", icon: <Icon.SearchFat /> },
  { name: "SearchFatAdd", icon: <Icon.SearchFatAdd /> },
  { name: "SearchFatMinus", icon: <Icon.SearchFatMinus /> },
  { name: "SearchMinus", icon: <Icon.SearchMinus /> },
  { name: "SearchThin", icon: <Icon.SearchThin /> },
  { name: "SearchThinAdd", icon: <Icon.SearchThinAdd /> },
  { name: "SearchThinMinus", icon: <Icon.SearchThinMinus /> },
  { name: "SelectionExclude", icon: <Icon.SelectionExclude /> },
  { name: "SelectionIntersect", icon: <Icon.SelectionIntersect /> },
  { name: "SelectionSubtract", icon: <Icon.SelectionSubtract /> },
  { name: "SelectionUnion", icon: <Icon.SelectionUnion /> },
  { name: "Server", icon: <Icon.Server /> },
  { name: "ServerMulti", icon: <Icon.ServerMulti /> },
  { name: "SettingHexagon", icon: <Icon.SettingHexagon /> },
  { name: "ShapePerspective", icon: <Icon.ShapePerspective /> },
  { name: "ShapeSquare", icon: <Icon.ShapeSquare /> },
  { name: "Share", icon: <Icon.Share /> },
  { name: "ShareCircle", icon: <Icon.ShareCircle /> },
  { name: "ShareDots", icon: <Icon.ShareDots /> },
  { name: "ShareFat", icon: <Icon.ShareFat /> },
  { name: "ShareFatSquare", icon: <Icon.ShareFatSquare /> },
  { name: "Shield", icon: <Icon.Shield /> },
  { name: "ShieldAdd", icon: <Icon.ShieldAdd /> },
  { name: "ShieldCheck", icon: <Icon.ShieldCheck /> },
  { name: "ShieldKey", icon: <Icon.ShieldKey /> },
  { name: "ShieldOff", icon: <Icon.ShieldOff /> },
  { name: "ShieldRemove", icon: <Icon.ShieldRemove /> },
  { name: "Shuffle", icon: <Icon.Shuffle /> },
  { name: "SidebarLeft", icon: <Icon.SidebarLeft /> },
  { name: "SidebarRight", icon: <Icon.SidebarRight /> },
  { name: "Skype", icon: <Icon.Skype /> },
  { name: "Slack", icon: <Icon.Slack /> },
  { name: "SliderHorizontal", icon: <Icon.SliderHorizontal /> },
  { name: "SliderVertical", icon: <Icon.SliderVertical /> },
  { name: "Snapchat", icon: <Icon.Snapchat /> },
  { name: "Sparks2Points", icon: <Icon.Sparks2Points /> },
  { name: "Sparks3Points", icon: <Icon.Sparks3Points /> },
  { name: "Sparks4Points", icon: <Icon.Sparks4Points /> },
  { name: "Spotify", icon: <Icon.Spotify /> },
  { name: "Square", icon: <Icon.Square /> },
  { name: "Star", icon: <Icon.Star /> },
  { name: "Star4Points", icon: <Icon.Star4Points /> },
  { name: "Star4PointsNarrow", icon: <Icon.Star4PointsNarrow /> },
  { name: "Star4PointsThin", icon: <Icon.Star4PointsThin /> },
  { name: "Star6Points", icon: <Icon.Star6Points /> },
  { name: "Star8Points", icon: <Icon.Star8Points /> },
  { name: "StarCircle", icon: <Icon.StarCircle /> },
  { name: "StarHalf", icon: <Icon.StarHalf /> },
  { name: "StarMoveHorizontal", icon: <Icon.StarMoveHorizontal /> },
  { name: "StarMoveVertical", icon: <Icon.StarMoveVertical /> },
  { name: "StarOff", icon: <Icon.StarOff /> },
  { name: "Sticker", icon: <Icon.Sticker /> },
  { name: "Sun", icon: <Icon.Sun /> },
  { name: "Support", icon: <Icon.Support /> },
  { name: "SwapHalfHorizontal", icon: <Icon.SwapHalfHorizontal /> },
  {
    name: "SwapHalfHorizontalReverse",
    icon: <Icon.SwapHalfHorizontalReverse />,
  },
  { name: "SwapHalfVertical", icon: <Icon.SwapHalfVertical /> },
  {
    name: "SwapHalfVerticalReverse",
    icon: <Icon.SwapHalfVerticalReverse />,
  },
  { name: "SwapHorizontal", icon: <Icon.SwapHorizontal /> },
  { name: "SwapHorizontalReverse", icon: <Icon.SwapHorizontalReverse /> },
  { name: "SwapVertical", icon: <Icon.SwapVertical /> },
  { name: "SwapVerticalReverse", icon: <Icon.SwapVerticalReverse /> },
  { name: "Table", icon: <Icon.Table /> },
  { name: "Telegram", icon: <Icon.Telegram /> },
  { name: "Terminal", icon: <Icon.Terminal /> },
  { name: "TerminalSquare", icon: <Icon.TerminalSquare /> },
  { name: "TerminalWindow", icon: <Icon.TerminalWindow /> },
  { name: "TextInput", icon: <Icon.TextInput /> },
  { name: "ThreeDotsHorizontal", icon: <Icon.ThreeDotsHorizontal /> },
  {
    name: "ThreeDotsHorizontalCircle",
    icon: <Icon.ThreeDotsHorizontalCircle />,
  },
  {
    name: "ThreeDotsHorizontalSquare",
    icon: <Icon.ThreeDotsHorizontalSquare />,
  },
  { name: "ThreeDotsVertical", icon: <Icon.ThreeDotsVertical /> },
  { name: "ThreeDotsVerticalCircle", icon: <Icon.ThreeDotsVerticalCircle /> },
  { name: "ThreeDotsVerticalSquare", icon: <Icon.ThreeDotsVerticalSquare /> },
  { name: "ToggleOff", icon: <Icon.ToggleOff /> },
  { name: "ToggleOn", icon: <Icon.ToggleOn /> },
  { name: "ToggleSquareOff", icon: <Icon.ToggleSquareOff /> },
  { name: "ToggleSquareOn", icon: <Icon.ToggleSquareOn /> },
  { name: "Tool", icon: <Icon.Tool /> },
  { name: "Tools", icon: <Icon.Tools /> },
  { name: "TouchId", icon: <Icon.TouchId /> },
  { name: "Translate", icon: <Icon.Translate /> },
  { name: "TranslateSquare", icon: <Icon.TranslateSquare /> },
  { name: "Trash", icon: <Icon.Trash /> },
  { name: "TrashForever", icon: <Icon.TrashForever /> },
  { name: "TrashLine", icon: <Icon.TrashLine /> },
  { name: "TrashLineForever", icon: <Icon.TrashLineForever /> },
  { name: "TrashLinePattern", icon: <Icon.TrashLinePattern /> },
  { name: "TrashLineRestore", icon: <Icon.TrashLineRestore /> },
  { name: "TrashPattern", icon: <Icon.TrashPattern /> },
  { name: "TrashRestore", icon: <Icon.TrashRestore /> },
  { name: "Triangle", icon: <Icon.Triangle /> },
  { name: "TriangleDown", icon: <Icon.TriangleDown /> },
  { name: "TriangleLeft", icon: <Icon.TriangleLeft /> },
  { name: "TriangleRight", icon: <Icon.TriangleRight /> },
  { name: "TriangleUp", icon: <Icon.TriangleUp /> },
  { name: "Undo", icon: <Icon.Undo /> },
  { name: "Unlike", icon: <Icon.Unlike /> },
  { name: "UnlockCircle", icon: <Icon.UnlockCircle /> },
  { name: "UnlockNarrow", icon: <Icon.UnlockNarrow /> },
  { name: "UnlockSquare", icon: <Icon.UnlockSquare /> },
  { name: "Upload", icon: <Icon.Upload /> },
  { name: "UploadCircle", icon: <Icon.UploadCircle /> },
  { name: "UploadCloud", icon: <Icon.UploadCloud /> },
  { name: "UploadSquare", icon: <Icon.UploadSquare /> },
  { name: "UseAsMask", icon: <Icon.UseAsMask /> },
  { name: "User", icon: <Icon.User /> },
  { name: "UserAdd", icon: <Icon.UserAdd /> },
  { name: "UserCard", icon: <Icon.UserCard /> },
  { name: "UserCircle", icon: <Icon.UserCircle /> },
  { name: "UserMinus", icon: <Icon.UserMinus /> },
  { name: "UserNarrow", icon: <Icon.UserNarrow /> },
  { name: "UserNarrowAdd", icon: <Icon.UserNarrowAdd /> },
  { name: "UserNarrowMinus", icon: <Icon.UserNarrowMinus /> },
  { name: "UserRounded", icon: <Icon.UserRounded /> },
  { name: "UserRoundedAdd", icon: <Icon.UserRoundedAdd /> },
  { name: "UserRoundedMinus", icon: <Icon.UserRoundedMinus /> },
  { name: "UserSquare", icon: <Icon.UserSquare /> },
  { name: "WarningCircle", icon: <Icon.WarningCircle /> },
  { name: "WarningHexagon", icon: <Icon.WarningHexagon /> },
  { name: "WarningOctagon", icon: <Icon.WarningOctagon /> },
  { name: "WarningSign", icon: <Icon.WarningSign /> },
  { name: "WarningSquare", icon: <Icon.WarningSquare /> },
  { name: "Webpage", icon: <Icon.Webpage /> },
  { name: "Wechat", icon: <Icon.Wechat /> },
  { name: "Whatsapp", icon: <Icon.Whatsapp /> },
  { name: "Width", icon: <Icon.Width /> },
  { name: "Window", icon: <Icon.Window /> },
  { name: "XTwitter", icon: <Icon.XTwitter /> },
  { name: "Youtube", icon: <Icon.Youtube /> },
  { name: "Zoom", icon: <Icon.Zoom /> },
];

function IconsLibraryTemplate() {
  const [search, setSearch] = React.useState<string>("");

  const filteredList = DefaultIconList.filter((icn) =>
    icn.name.toLowerCase().includes(search.trim().toLowerCase()),
  );
  const deferredList = React.useDeferredValue(filteredList, DefaultIconList);
  const iconsList = search.length !== 0 ? deferredList : DefaultIconList;

  return (
    <React.Fragment>
      <Field.Root>
        <Field.Wrapper className="flex align-center w-100">
          <Icon>
            <Icon.Search />
          </Icon>
          <Field
            placeholder="Search icons.."
            value={search}
            onChange={(e) => setSearch(e.target.value)}
            variant="ghost"
            sizing="medium"
            style={{ width: "100%" }}
          />
        </Field.Wrapper>
      </Field.Root>
      {/* <p className="opacity-default-30 fs-medium-10">
        Click an Icon to copy the code
      </p> */}
      <GridLayout>
        {iconsList.map(
          (
            defaultIcon: { name: string; icon: React.ReactNode },
            key: number,
          ) => (
            <Box key={key}>
              <CopyButton
                value={`<Icon><Icon.${defaultIcon.name} /></Icon>`}
                tooltip={{
                  copyLabel: `Copy ${defaultIcon.name}`,
                }}
              >
                <Icon>{defaultIcon.icon}</Icon>
              </CopyButton>

              <p className="opacity-default-30 fs-medium-10">
                {defaultIcon.name}
              </p>
            </Box>
          ),
        )}
      </GridLayout>
    </React.Fragment>
  );
}

export default IconsLibraryTemplate;
